// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload() {
  return window['go']['main']['App']['CancelModelDownload']();
}

export function ClearConversationHistory() {
  return window['go']['main']['App']['ClearConversationHistory']();
}

export function GetDownloadedModels() {
  return window['go']['main']['App']['GetDownloadedModels']();
}

export function GetModelDirectory() {
  return window['go']['main']['App']['GetModelDirectory']();
}

export function GetSearchConfig() {
  return window['go']['main']['App']['GetSearchConfig']();
}

export function GetSystemConfig() {
  return window['go']['main']['App']['GetSystemConfig']();
}

export function GetSystemSpec() {
  return window['go']['main']['App']['GetSystemSpec']();
}

export function GetSystemUsage() {
  return window['go']['main']['App']['GetSystemUsage']();
}

export function LaunchOverlayWindow() {
  return window['go']['main']['App']['LaunchOverlayWindow']();
}

export function SaveSearchConfig(arg1) {
  return window['go']['main']['App']['SaveSearchConfig'](arg1);
}

export function SelectModelDirectory() {
  return window['go']['main']['App']['SelectModelDirectory']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCharacterProfile(arg1) {
  return window['go']['main']['App']['SetCharacterProfile'](arg1);
}

export function SetClickThrough(arg1) {
  return window['go']['main']['App']['SetClickThrough'](arg1);
}

export function SetLLMPreset(arg1) {
  return window['go']['main']['App']['SetLLMPreset'](arg1);
}

export function SetLive2DParameter(arg1, arg2) {
  return window['go']['main']['App']['SetLive2DParameter'](arg1, arg2);
}

export function SetModelDirectory(arg1) {
  return window['go']['main']['App']['SetModelDirectory'](arg1);
}

export function SetTTSProvider(arg1, arg2) {
  return window['go']['main']['App']['SetTTSProvider'](arg1, arg2);
}

export function StartModelDownload(arg1) {
  return window['go']['main']['App']['StartModelDownload'](arg1);
}

export function StartServices() {
  return window['go']['main']['App']['StartServices']();
}

export function StopServices() {
  return window['go']['main']['App']['StopServices']();
}

export function SwitchClassifierModel(arg1) {
  return window['go']['main']['App']['SwitchClassifierModel'](arg1);
}

export function SwitchDisplayMode(arg1) {
  return window['go']['main']['App']['SwitchDisplayMode'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function UpdateSystemConfig(arg1) {
  return window['go']['main']['App']['UpdateSystemConfig'](arg1);
}
