// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {websearch} from '../models';
import {main} from '../models';
import {platform} from '../models';
import {llm} from '../models';

export function CancelModelDownload():Promise<void>;

export function ClearConversationHistory():Promise<void>;

export function GetDownloadedModels():Promise<Array<string>>;

export function GetModelDirectory():Promise<string>;

export function GetSearchConfig():Promise<websearch.SearchConfig>;

export function GetSystemConfig():Promise<main.SystemConfig>;

export function GetSystemSpec():Promise<platform.SystemSpec>;

export function GetSystemUsage():Promise<platform.SystemUsage>;

export function LaunchOverlayWindow():Promise<void>;

export function SaveSearchConfig(arg1:websearch.SearchConfig):Promise<void>;

export function SelectModelDirectory():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCharacterProfile(arg1:llm.CharacterProfile):Promise<void>;

export function SetClickThrough(arg1:boolean):Promise<void>;

export function SetLLMPreset(arg1:string):Promise<void>;

export function SetLive2DParameter(arg1:string,arg2:number):Promise<void>;

export function SetModelDirectory(arg1:string):Promise<void>;

export function SetTTSProvider(arg1:string,arg2:number):Promise<void>;

export function StartModelDownload(arg1:string):Promise<void>;

export function StartServices():Promise<void>;

export function StopServices():Promise<void>;

export function SwitchClassifierModel(arg1:string):Promise<void>;

export function SwitchDisplayMode(arg1:string):Promise<void>;

export function SwitchModel(arg1:string):Promise<void>;

export function UpdateSystemConfig(arg1:main.SystemConfig):Promise<void>;
